import { Button } from '@/components/Button/Button';
import { useUserContext } from '@/context';
import { Password, RegisterLink, SigninLink, Username } from '@/lang';
import styles from '@/styles/Home.module.css';
import { UserInfo } from '@/types';
import Cookies from 'js-cookie';
import Head from 'next/head';
import Link from 'next/link';
import Router from 'next/router';
import { useState } from 'react';

const baseUrl = process.env.NEXT_PUBLIC_API_URL;

/**
 * Innskráir notanda
 */
const loginHandler = async (event: any): Promise<UserInfo> => {
  event.preventDefault();
  const username = event.target.username.value;
  const password = event.target.password.value;

  let res;
  try {
    res = await fetch(`${baseUrl}/users/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: '*/*',
        'Accept-Encoding': 'gzip, deflate, br',
        Connection: 'keep-alive',
      },
      body: JSON.stringify({ username, password }),
    });
  } catch(e: any) {
    console.error('Error:', e.message)
    throw new Error(e || 'Unknown error');
  }

  if (res && !res.ok) {
    console.error('Error:', res.status, res.statusText);
    const message = await res.json();
    console.error(message.error)
    throw new Error(message.error || 'Unknown error');
  }

  const result = await res.json();

  if (result.user !== undefined) {
    Cookies.set('token', result.token, { expires: 5 });
  }

  return result;
};

export default function Login() {
  const loginContext = useUserContext();
  // const [fail, setFail] = useState(false);
  const [error, setError] = useState(null);

  const language = process.env.NEXT_PUBLIC_LANGUAGE || 'ENG';


  return (
      <>
        <Head>
          <title>{SigninLink[language]}</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="utf-8"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.loginForm}>

            <h1>{SigninLink[language]}</h1>

            <form className={styles.form}
              onSubmit={async (event) => {
                event.preventDefault();

         
                  let userInfo;
                  try {
                    userInfo = await loginHandler(event);
                  } catch(e: any) {
                    setError(e.message);
                  }
                  
                  if (userInfo && userInfo.user !== undefined) {
                    loginContext.setUserLoggedIn({ login: true, user: userInfo.user });
                    Cookies.set('user', JSON.stringify({ login: true, user: userInfo.user }), { expires: 3 });
                    // setFail(false);

                    if(userInfo.user.admin) {
                      Router.push('/admin');
                    } else {
                      Router.push('/');
                    }
                  } 
                  // else {
                  //   setFail(true);
                  // }

              }}
            >
              <label htmlFor='username'>{Username[language]}</label>

              <input type='text' id='username' required/>

              <label htmlFor='password'>{Password[language]}</label>

              <input type='password' id='password' required/>

              {/* {fail ? <p>Ógilt notandanafn/lykilorð</p> : <p></p>} */}
              <Button type='submit'>{SigninLink[language]}</Button>
            </form>

            <Link href='/register'>{RegisterLink[language]}</Link>

            {error && <h3>{error}</h3>}
          </div>
        </main>
      </>
  )
    
}