import { Button } from '@/components/Button/Button';
import { Email, Password, RegisterLink, Username } from '@/lang';
import styles from '@/styles/Home.module.css';
import { User } from '@/types';
import Head from 'next/head';
import Router from 'next/router';
import { useState } from 'react';

const baseUrl = process.env.NEXT_PUBLIC_API_URL;

/**
 * Nýskráir notanda
 */
const registerHandler = async (event: any): Promise<User> => {
  event.preventDefault();

  const username = event.target.username.value;
  const email = event.target.email.value;
  const password = event.target.password.value;

  let res;
  try {
    res = await fetch(`${baseUrl}/users/register`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: '*/*',
        'Accept-Encoding': 'gzip, deflate, br',
        Connection: 'keep-alive',
      },
      body: JSON.stringify({ username, email, password }),
    });    
  } catch(e: any) {
    console.error('Error:', e.message)
    throw new Error(e || 'Unknown error');
  }

  if (res && !res.ok) {
    console.error('Error:', res.status, res.statusText);
    const message = await res.json();
    console.error(message.error)
    throw new Error(message.error || 'Unknown error');
  }

  const result = await res.json();

  return result;
};


export default function Register() {
  // const [fail, setFail] = useState(false);
  const [error, setError] = useState(null);

  const language = process.env.NEXT_PUBLIC_LANGUAGE || 'ENG';

  return (
      <>
        <Head>
          <title>{RegisterLink[language]}</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="utf-8"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.loginForm}>

            <h1>{RegisterLink[language]}</h1>
            <form className={styles.form}
              onSubmit={async (event) => {
                event.preventDefault();

                try {
                  const userInfo = await registerHandler(event);

                  if (userInfo.username !== undefined) {
                    // setFail(false);
                    Router.push('/login');
                  } 
                  // else {
                  //   setFail(true);
                  // }                  
                } catch(e: any) {
                  setError(e.message);
                }
              }}
            >
              <label htmlFor='username'>{Username[language]}:</label>

              <input type='text' id='username' required/>

              <label htmlFor='email'>{Email[language]}:</label>

              <input type='text' id='email' required/>

              <label htmlFor='password'>{Password[language]}:</label>

              <input type='password' id='password' required/>
              
              {/* {fail ? <p>Ógilt lykilorð/password</p> : <p></p>} */}
              <Button type='submit'>{RegisterLink[language]}</Button>
            </form>

            {error && <h3>{error}</h3>}

          </div>
        </main>
      </>
  )
    
}